language: python
python:
  - "2.7"
cache: pip
install:
  - mkdir -p /home/travis/jd2/folderwatch
  - pip install -r requirements.txt
script:
  - python RSScrawler.py --port=9090 --jd-pfad="/home/travis/jd2" --ersatzblogs --testlauf --log-level=DEBUG
