language: python
python:
  - "2.7"
  - "3.6"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
      cache: pip
    - python: 3.8-dev
      dist: xenial
      sudo: true
      cache: pip
allow_failures:
  - python: 3.8-dev
cache: pip
install:
  - mkdir -p /home/travis/jd2/folderwatch
  - pip install -r requirements.txt
script:
  - python RSScrawler.py --port=9090 --jd-pfad="/home/travis/jd2" --testlauf --log-level=DEBUG
